export default {
  name: 'content',
  type: 'array',
  title: 'Komponenty podstrony',
  of: [
    {type: 'HeroColumnWithImageReactor'},
    {type: 'HeroWithRotatingElipsis'},
    {type: 'HeadingGrid'},
    {type: 'HeadingWithNumeratedList'},
    {type: 'AdvancedCtaSection'},
    {type: 'HeroImageBackground'},
    {type: 'ListPillWithIconHeading'},
    {type: 'CtaSectionWithImage'},
    {type: 'RevealImage'},
    {type: 'Newsletter'},
    {type: 'CompaniesShowcase'},
    {type: 'KeyDetails'},
    {type: 'Perks'},
    {type: 'Benefits'},
    {type: 'CtaSection'},
    {type: 'StatsList'},
    {type: 'Recipients'},
    {type: 'Reviews'},
    {type: 'Idea'},
    {type: 'Certificate'},
    {type: 'Lessons'},
    {type: 'Faq'},
    {type: 'Author'},
    {type: 'image', name: 'LargeImage', title: 'Duże zdjęcie'},
    {type: 'Charts'},
  ],
}
